parse_temp:
	@gcc -Wall -O2 test_parse_temp.c -o test

tempval_to_str:
	@gcc -Wall -O2 test_tempval_to_str.c -o test

bcd:
	@gcc -Wall -O2 test_bcd.c -o test

rtc:
	@gcc -Wall -O2 test_rtc_conv.c -o test

conv_date:
	@gcc -Wall -O2 test_date2s.c -o test

clean:
	@-rm -f test

.PHONY: all clean
