MKDIR_P = mkdir -p

STYLECHECK	:= checkpatch.pl
STYLECHECKFLAGS	:= -f --terse --mailback
STYLECHECKFILES	:= $(shell find src/ include/ -name '*.[ch]')

stylecheck: $(STYLECHECKFILES:=.stylecheck)
styleclean:
	$(Q)find . -type f -name '*.stylecheck' -delete
	$(Q)find . -type f -name '*.checkpatch-*' -delete

# The cat is due to multithreaded nature - we like to have consistent chunks of
# text on the output
%.stylecheck: %
	$(Q)$(SCRIPT_DIR)/$(STYLECHECK) $(STYLECHECKFLAGS) $* > $*.stylecheck; \
		if [ -s $*.stylecheck ]; then	\
			cat $*.stylecheck;	\
		else				\
			rm -f $*.stylecheck;	\
		fi;

doxy:
	@printf "  DOXY\n"
	$(Q)$(MKDIR_P) doc/doxy
	$(Q)doxygen

doxy_clean:
	$(Q)$(RM) -rf doc/doxy

check_float: elf
	@printf " CHECK_FLOAT\n"
	$(Q)$(SCRIPT_DIR)/check-float.sh

gdb: $(APP).elf
	@$(SCRIPT_DIR)/gdb.sh $(APP).elf

ddd: $(APP).elf
	@$(SCRIPT_DIR)/gdb.sh --ddd $(APP).elf

help:
	@echo
	@echo "Debugging:"
	@echo "  gdb                  - start gdb debugging session"
	@echo "  ddd                  - start gdb debugging session using DDD"

.PHONY: stylecheck styleclean doxy doxy_clean check_float help gdb ddd
